### ISSUE TITLE
How to run transformer model

### ISSUE THREAD

**Issue by Vpredictor** [SuperBruceJia/EEG-DL#12]
Currently, I am stuck in preprocessing. Which preprocessor should I use to generate corresponding files, eg. training_set.csv, training_label.csv, test_set.csv, test_label.csv.

**Comment by SuperBruceJia** [comment]
Hi, thanks for your interest in our work. I'm here to help.

First of all, please follow the usage demo [here](https://github.com/SuperBruceJia/EEG-DL#Usage-Demo) to obtain the processed dataset, i.e., training and testing data.

Then, I encourage you to edit [this code](https://github.com/SuperBruceJia/EEG-DL/blob/master/Models/main-Transformer.py) to train a Transformer model. 

If you encounter any problems, post them here and I'll try to fix them for you.

Best regards,

Shuyue
May 17, 2022
