### ISSUE TITLE
Training Transformer Model

### ISSUE THREAD

**Issue by dimlightray** [SuperBruceJia/EEG-DL#16]
Hi, I'm trying to train Transformer Model code with "**EEG Motor Movement/Imagery Dataset**".

I found that the **maxlen = 3, embed_dim = 97** in main-Transformer.py code.

The current input shape of transformer model is **3 * 97 = 291**.

However, after I ran make_dataset.m code, I got **4096 (64 * 64)** data shape.

So I wonder why the input shape of main-Transformer.py is **291 instead of 4096**.

**Comment by SuperBruceJia** [comment]
> Hi, I'm trying to train Transformer Model code with "**EEG Motor Movement/Imagery Dataset**".
> 
> I found that the **maxlen = 3, embed_dim = 97** in main-Transformer.py code.
> 
> The current input shape of transformer model is **3 * 97 = 291**.
> 
> However, after I ran make_dataset.m code, I got **4096 (64 * 64)** data shape.
> 
> So I wonder why the input shape of main-Transformer.py is **291 instead of 4096**.

Hi, good morning! 

The `main-Transformer.py` code is just a toy demo, which can be used in your case. You can modify the `maxlen` and `embed_dim` arguments to fit your personal data. For example, if your data is [*64 channels data* X *64 time points*], the `maxlen` should be the *64 time points* and `embed_dim` should be the *64 channels data*. At the same time, you may also add a `positional embedding` to the 64 time points' embedded features to prevent permutation invariance. 

If you have additional questions, please let me know.

Best regards,

Shuyue
Nov. 8th, 2022

**Comment by nehagour** [comment]
Thank you for the reply. Can you tell us little bit about how to implemented positional embedding?

**Comment by SuperBruceJia** [comment]
> Thank you for the reply. Can you tell us little bit about how to implemented positional embedding?

[1] In fact, there is a uniformly-initialized positional embedding in the [TensorFlow Code](https://github.com/SuperBruceJia/EEG-DL/blob/4d6a63011951e8b443cdd1f470f23f12916a0ddd/Models/main-pretrain_model.py#L88), from line 88 to 101. The usage of the positional embedding is to consider the order of the input time series. Thus, it can prevent the permutation invariance inductive bias inside the Transformer Model (or Graph Neural Network models). 

[2] You may also refer to the Transformer paper: Attention is all you need, which used the sine and cosine functions of different frequencies for positional embedding.

If you have additional questions, please let me know.

Best regards,

Shuyue
Nov. 8th, 2022

**Comment by nehagour** [comment]
Thanks for the clarification. Can you tell me if the transformer you have implemented act as a Vision Transformer for EEG signals? I am trying to understand how the original transformer is adopted for the multivariate signal classification i.e. in our case EEG signals with more than on electrodes.

**Comment by SuperBruceJia** [comment]
> Thanks for the clarification. Can you tell me if the transformer you have implemented act as a Vision Transformer for EEG signals? I am trying to understand how the original transformer is adopted for the multivariate signal classification i.e. in our case EEG signals with more than on electrodes.

What I implemented was a simple Transformer Decoder with uniformly-initialized positional embedding, which was not ViT (Vision Transformer) or Swin Transformer. You may refer to the ViT or Swin Transformer official repo for detailed implementation.
