### ISSUE TITLE
EEG input shape for transformer model

### ISSUE THREAD

**Issue by nehagour** [SuperBruceJia/EEG-DL#17]
I am training the transformer for EEG input shape as (26,11000) where "26" is number of channels(electrodes) and 11k are features. I am not able to understand how I should apply such input to the code.

**Comment by SuperBruceJia** [comment]
> I am training the transformer for EEG input shape as (26,11000) where "26" is number of channels(electrodes) and 11k are features. I am not able to understand how I should apply such input to the code.

Morning!

Please refer to [this issue](https://github.com/SuperBruceJia/EEG-DL/issues/16) to run the Transformer model.
If you have additional questions, please let me know.

Best regards,

Shuyue
Nov. 8th, 2022
