### ISSUE TITLE
#GCN，make_dataset.m

### ISSUE THREAD

**Issue by zh0501** [SuperBruceJia/EEG-DL#19]
作者你好，我在使用MATLAB运行make_dataset.m时，出现下述报错，我查询了百度，根据建议我禁止excel的com加载项，但结果还是不行，请问这是我电脑的内存问题还是什么别的呢？
![image](https://user-images.githubusercontent.com/102654153/203723803-a896933d-8165-4d91-8861-0ffe6fd796be.png)

**Comment by SuperBruceJia** [comment]
> 作者你好，我在使用MATLAB运行make_dataset.m时，出现下述报错，我查询了百度，根据建议我禁止excel的com加载项，但结果还是不行，请问这是我电脑的内存问题还是什么别的呢？ ![image](https://user-images.githubusercontent.com/102654153/203723803-a896933d-8165-4d91-8861-0ffe6fd796be.png)

Could I know how many memories your laptop has? The reason for this problem may be **the lack of memory** when saving the training data into an Excel file.

**Comment by SuperBruceJia** [comment]
> I also encountered the same problem, and replaced xlswrite with writematrix solved with 16G memories

@oopstls Thank you very much for your solution! 
@zh0501 You may use `writematrix` instead.

**Comment by zh0501** [comment]
@oopstls  Thank you very much，your suggestion is appropriate， my problem is solved
@SuperBruceJia Thank you very much for your reply too

**Comment by dadayu990518** [comment]
作者您好，想请问一下您，在数据处理步骤我按照前面朋友们给的建议把xlswrite换成writematrix用16G内存，数据处理完成，在训练时候代码运行出现这种情况，想请问一下
![微信图片_20230221152644](https://user-images.githubusercontent.com/116569874/220280519-14731bf2-3c45-4740-b59f-176018750d50.png)

**Comment by SuperBruceJia** [comment]
> 作者您好，想请问一下您，在数据处理步骤我按照前面朋友们给的建议把xlswrite换成writematrix用16G内存，数据处理完成，在训练时候代码运行出现这种情况，想请问一下 ![微信图片_20230221152644](https://user-images.githubusercontent.com/116569874/220280519-14731bf2-3c45-4740-b59f-176018750d50.png)

此时需要执行[main-GCN.py](https://github.com/SuperBruceJia/EEG-DL/blob/master/Models/main-GCN.py)文件。

**Comment by dadayu990518** [comment]
> > 作者好，想您您，在在处理步骤我我按照给的的的把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把![微信图片_20230221152644](https://user-images.githubusercontent.com/116569874/220280519-14731bf2-3c45-4740-b59f-176018750d50.png)
> 
> 此时需要执行[main-GCN.py](https://github.com/SuperBruceJia/EEG-DL/blob/master/Models/main-GCN.py)文件。

好的感谢作者，请问一下您可以指点一下这个代码的具体配置要求吗（机器环境）？

**Comment by dadayu990518** [comment]
> > 作者好，想您您，在在处理步骤我我按照给的的的把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把把![微信图片_20230221152644](https://user-images.githubusercontent.com/116569874/220280519-14731bf2-3c45-4740-b59f-176018750d50.png)
> 
> 此时需要执行[main-GCN.py](https://github.com/SuperBruceJia/EEG-DL/blob/master/Models/main-GCN.py)文件。

好的感谢作者，请问一下您可以指点一下这个代码的具体配置要求吗（机器环境）？我用的tf1.15，遇到了GCN网络输入不正确，是数据处理方面的问题还是?

**Comment by dadayu990518** [comment]
> 

谢谢，作者，麻烦再请教您一下，我在训练的过程中出现了 validation accuracy一直是一个数值不发生变化，是我数据处理的问题还是？谢谢作者!
![223005713-5313d573-c368-4d74-9f2a-df798b6add4a](https://user-images.githubusercontent.com/116569874/223935411-4a2537d1-5502-4aa0-a776-d92ba2805a9e.png)

**Comment by zh0501** [comment]
作者，你好请问你使用的GPU是什么？我训练模型需要的时间非常长，是有什么问题吗

**Comment by dadayu990518** [comment]
> 作者，你好请问你使用的GPU是什么？我训练模型需要的时间非常长，是有什么问题吗

您好，您跑出来，可以请问您一些问题吗，GCN网络输入格式不正确这边快您是怎么处理？
谢谢您

**Comment by zh0501** [comment]
我使用的笔记本的1650ti，运行的非常慢，后来就没搞这个方法了
















在 2023-04-07 12:47:55，"dadayu990518" ***@***.***> 写道：

作者，你好请问你使用的GPU是什么？我训练模型需要的时间非常长，是有什么问题吗

您好，您跑出来，可以请问您一些问题吗，GCN网络输入格式不正确这边快您是怎么处理？
谢谢您
