### ISSUE TITLE
Issues about GCN_MODEL data processing

### ISSUE THREAD

**Issue by daysofchasingdream** [SuperBruceJia/EEG-DL#20]
作者您好，阅读您的代码让我感觉到学习到很多东西，很有用处，但是有个小问题想请问一下您。
在GCN_model中，您是如何得到dataset.mat的，我认为您的处理方式如下，不知道我理解的对不对。您得到的dataset.mat文件中，每个mat文件的shape是[20,84,640]，我理解是20代表被试，640代表每次实验的跨度时间4×采样频率160=640（这个代表时间），那其中84=4×21，这里面的21是什么意思呢。
现在想要用在自己的数据集上，我可否尝试使用您的代码，我的数据格式是每个被试就单独的一个csv文件，文件内包括不同的动作，其中每一行是代表一个时间节点，每一列是代表一个通道，我可否直接将所有的被试csv纵向叠加，这样得到的结果和您的数据集traing_set格式是一样的吗？
提前谢谢您，祝您一切顺利。
（Hello author, reading your code makes me feel that I have learned a lot and it is very useful, but I have a small question to ask you.
In GCN_model, how did you get the dataset.mat? I think you handled it in the following way, I don't know if I understand it right. The shape of each mat file in the dataset.mat file you got is [20,84,640], I understand that 20 represents the subjects, 640 represents the span time of each experiment 4*sampling frequency 160=640 (this represents time), then where 84=4*21, what does the 21 in this mean.
Now I want to use it on my own dataset, can I try to use your code, my data format is a separate csv file for each subject, the file includes different actions, where each line is representing a time node, each column is representing a channel, can I directly superimpose all the subjects csv vertically, so that the results obtained and your dataset traing_set format is the same?
Thank you in advance and wish you all the best.）

**Comment by haoxiaodao** [comment]
为什么所有的标签都是“3”呢，这能出结果吗

**Comment by SuperBruceJia** [comment]
> 作者您好，阅读您的代码让我感觉到学习到很多东西，很有用处，但是有个小问题想请问一下您。 在GCN_model中，您是如何得到dataset.mat的，我认为您的处理方式如下，不知道我理解的对不对。您得到的dataset.mat文件中，每个mat文件的shape是[20,84,640]，我理解是20代表被试，640代表每次实验的跨度时间4×采样频率160=640（这个代表时间），那其中84=4×21，这里面的21是什么意思呢。 现在想要用在自己的数据集上，我可否尝试使用您的代码，我的数据格式是每个被试就单独的一个csv文件，文件内包括不同的动作，其中每一行是代表一个时间节点，每一列是代表一个通道，我可否直接将所有的被试csv纵向叠加，这样得到的结果和您的数据集traing_set格式是一样的吗？ 提前谢谢您，祝您一切顺利。 （Hello author, reading your code makes me feel that I have learned a lot and it is very useful, but I have a small question to ask you. In GCN_model, how did you get the dataset.mat? I think you handled it in the following way, I don't know if I understand it right. The shape of each mat file in the dataset.mat file you got is [20,84,640], I understand that 20 represents the subjects, 640 represents the span time of each experiment 4_sampling frequency 160=640 (this represents time), then where 84=4_21, what does the 21 in this mean. Now I want to use it on my own dataset, can I try to use your code, my data format is a separate csv file for each subject, the file includes different actions, where each line is representing a time node, each column is representing a channel, can I directly superimpose all the subjects csv vertically, so that the results obtained and your dataset traing_set format is the same? Thank you in advance and wish you all the best.）

<img width="1481" alt="image" src="https://user-images.githubusercontent.com/31528604/216864457-279d6aac-8f8f-4145-9ed1-bbc9f00aa277.png">

Please check my [presentation](https://shuyuej.com/files/Presentation/A_Summary_Three_Projects.pdf).

`现在想要用在自己的数据集上，我可否尝试使用您的代码，我的数据格式是每个被试就单独的一个csv文件，文件内包括不同的动作，其中每一行是代表一个时间节点，每一列是代表一个通道，我可否直接将所有的被试csv纵向叠加，这样得到的结果和您的数据集traing_set格式是一样的吗？ `

当然可以呀。至于CSV文件：data csv就是每一行代表一个样本，label csv就是每一行代表一个label。
`一个样本` 可以是一个时间点(时刻)的数据，也可以是一个时间段的数据，比如说4秒的数据，那一行有640个点（数值），代表4 X 160。

If you have any other questions, please let me know.

Shuyue
Feb. 6th, 2023
