### ISSUE TITLE
Error in GCN Model

### ISSUE THREAD

**Issue by Panos13L** [SuperBruceJia/EEG-DL#22]
I change the code to fit in my dataset for GCN but when I try to fit my model, I take the following error in fit function at GCN_Model.py:
Attempt to convert a value (<tensorflow.python.framework.ops.Graph object at 0x000001C06CCFBA90>) with an unsupported type (<class 'tensorflow.python.framework.ops.Graph'>) to a Tensor. Anyone knows what cause this error and how can I fix it?

**Comment by SuperBruceJia** [comment]
Please Google the error. 

If you have any other questions, please let me know.

Shuyue
Feb. 6th, 2023
