### ISSUE TITLE
Extract-Raw-Data-Into-Matlab-Files.py这个文件的代码是不是不完整

### ISSUE THREAD

**Issue by haoxiaodao** [SuperBruceJia/EEG-DL#23]
通过这个文件生成的matlab文件（20×84×640），感觉没有意义，然后生成的labels文件，标签值都是3，这样的数据，怎么能用呢？作者是不是没有把完整的文件放上来呀？

**Comment by SuperBruceJia** [comment]
Please note that this file should be executed under the `Python 2.7` environment. Otherwise, the labels will be wrong.

Let me know if you have other questions.

Shuyue
Feb. 6th, 2023

**Comment by haoxiaodao** [comment]
> Please note that this file should be executed under the `Python 2.7` environment. Otherwise, the labels will be wrong.
> 
> Let me know if you have other questions.
> 
> Shuyue Feb. 6th, 2023
感谢您的回复，但是我感觉这和python环境应该没关系吧

**Comment by SuperBruceJia** [comment]
> 的回复，但是我感觉这和python环境应该没关系吧

有关系的！因为这个代码使用了Python 2的部分语法，所以需要在Python 2.7的环境下run。如果在Python 3下run，结果会有问题的。**如果您把这个文件中的部分代码修改后，可以在Python 3下run，也希望您能把代码pull到repo中，谢谢！**

**Comment by haoxiaodao** [comment]
> > 的回复，但是我感觉这和python环境应该没关系吧
> 
> 有关系的！因为这个代码使用了Python 2的部分语法，所以需要在Python 2.7的环境下run。如果在Python 3下run，结果会有问题的。`这也是我特意强调要用Python 2.7的环境的！`**如果您把这个文件中的部分代码修改后，可以在Python 3下run，也希望您能把代码pull到repo中，谢谢！**

感谢您的回复，我的代码能力有限，我试试吧

**Comment by ceciliaxu1** [comment]
请问有python3环境下的代码吗，我在python3环境中运行报错
# python3 Download_Raw_EEG_Data/Extract-Raw-Data-Into-Matlab-Files.py 
Start to save the Files!
Traceback (most recent call last):
  File "Download_Raw_EEG_Data/Extract-Raw-Data-Into-Matlab-Files.py", line 250, in <module>
    X, Y = load_raw_data(electrodes=electrodes, subject=subject, num_classes=nclasses)
  File "Download_Raw_EEG_Data/Extract-Raw-Data-Into-Matlab-Files.py", line 209, in load_raw_data
    return np.array(trials, dtype=np.float64).reshape((len(trials),) + trials[0].shape + (1,)), \
IndexError: list index out of range

**Comment by SuperBruceJia** [comment]
> 请问有python3环境下的代码吗，我在python3环境中运行报错
> 
> # python3 Download_Raw_EEG_Data/Extract-Raw-Data-Into-Matlab-Files.py
> Start to save the Files! Traceback (most recent call last): File "Download_Raw_EEG_Data/Extract-Raw-Data-Into-Matlab-Files.py", line 250, in X, Y = load_raw_data(electrodes=electrodes, subject=subject, num_classes=nclasses) File "Download_Raw_EEG_Data/Extract-Raw-Data-Into-Matlab-Files.py", line 209, in load_raw_data return np.array(trials, dtype=np.float64).reshape((len(trials),) + trials[0].shape + (1,)), IndexError: list index out of range

请follow [Usage Demo](https://github.com/SuperBruceJia/EEG-DL#Usage-Demo) 使用`Python 2.7`环境。

**Comment by sergi24sanchez** [comment]
What should be changed to be able to execute the file with python 3 instead of 2.7?
