### ISSUE TITLE
EEG-Motor-Imagery-Classification-CNNs-TensorFlow

### ISSUE THREAD

**Issue by sangwan130** [SuperBruceJia/EEG-DL#26]
i am using Read_Raw_Data_Save_Into_Matlab_Files.py for physionet dataset and error occurs is 

X_105_C5, y_105_C5 = load_raw_data(electrodes=electrodes, subject=subject, num_classes=nclasses)
  File " \Read_Raw_Data_Save_Into_Matlab_Files.py", line 200, in load_raw_data
    return np.array(trials, dtype=np.float64).reshape((len(trials),) + trials[0].shape + (1,)), np.array(labels, dtype=np.float64)
IndexError: list index out of range

Can you help me to sort out this or provide link for dataset with labels

**Comment by SuperBruceJia** [comment]
**IndexError: list index out of range**
    
To resolve this issue, ensure that you are using the `Python 2.7` Environment and have installed the pyEDFlib 0.1.11 version. Please follow the installation instructions given below:

```python
$ pip install pyEDFlib==0.1.11
```

Please let me know if you have additional questions.

Best regards,

Shuyue
Dec. 30th, 2023
