### ISSUE TITLE
Features from BiLSTM to Graph Adjacency Matrix

### ISSUE THREAD

**Issue by guxiao0822** [SuperBruceJia/EEG-DL#7]
Hi, thanks for your nice work!

I am wondering how to generate the adjacency matrix from the features of BiLSTM, as mentioned in "Deep Feature Mining via Attention-based BiLSTM-GCN for Human Motor Imagery Recognition" 

I guess your BiLSTM should be channel-wise but I cannot find a clear statement in your paper.  If so, only FC considers the spatial relationship, would it be effective enough?

**Comment by SuperBruceJia** [comment]
Hi,

Thanks for your interest in our work.

As for the Adjacency Matrix, please refer to [this file](https://github.com/SuperBruceJia/EEG-DL/blob/master/Preprocess_EEG_Data/For-GCN-based-Models/make_dataset.m). To be specific, this file is using all the raw EEG signals to make a Pearson Matrix as an Adjacency Matrix. In contrast, your referred paper is using all the features extracted by the LSTM model. As a result, the codes are the same while the data is not.

If u have additional questions, please let me know.

Best,

Shuyue
